name: feature-pipeline
on:   workflow_dispatch
  # push:


jobs:
  feature-pipeline:
    if: github.ref_name != 'main'
    uses: prasanna0805/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with: 
      project: 'roboshop'
      component: 'catalogue'  
    secrets: inherit
 