name: feature-pipeline
on: 
  push:
  workflow_dispatch:

jobs:
  feature-pipeline:
    if: github.ref_name != 'main'
    uses: prasanna0805/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with: 
      project: 'roboshop'
      component: 'catalogue'  
 